# Generated by Django 2.2.10 on 2020-02-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200218_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'Выдана'), ('a', 'Доступна'), ('r', 'Reserved')], default='m', help_text='Доступность книги', max_length=1),
        ),
    ]
